### ISSUE TITLE
About the posterior calculation

### ISSUE THREAD

**Issue by XunshanMan** [BeipengMu/objectSLAM#4]
Hi, I have a small question about the calculation of the posterior.
In the paper, it contains a prior of Dirichlet Process, and the likelihood of object detection.
In the code, 

dp_prior = p(obj.measurements.label(k),:);
sq_dist = sum((obj_poses - repmat(pos,1,N)).^2,1);
posterior = exp(-4*sq_dist).*dp_prior;
[prob, I]=max(posterior);

1. I'm wondering why the dp_prior is an integer, beacause after several observations, the posterior will be far more than 1.
2. the coefficient -4, is that mean -1/(0.5)^2? an assumption of the gaussian distribution of the object position, with a sigma of 0.5m?

I just read your paper. I'm wondering if I understood it right.
Thanks for your help!

**Comment by mubeipeng** [comment]
1. the original DP, prior is proportional to the number of observations. p(n) ~ n/(N+alpha), where N is the total number of observations so far, and alpha is a factor. Since (N+alpha) is a constant multiplier for all classes, it does not affect the max-posterior calculation, so the calculation could be simplied.
2. that's probably right as far as I can recall

**Comment by XunshanMan** [comment]
Happy to hear your response so fast. 
Thanks, that really helps.
